import {
  Briefcase,
  Wallet,
  DollarSign,
  PiggyBank,
  TrendingUp,
  Coins,
  Dumbbell,
  Bike,
  Footprints,
  Activity,
  Trophy,
  Flame,
  Mountain,
  Waves,
  Heart,
  HeartPulse,
  Pill,
  Stethoscope,
  Brain,
  Moon,
  Bed,
  Droplet,
  Baby,
  GraduationCap,
  BookOpen,
  NotebookPen,
  Languages,
  Home,
  Wrench,
  ShoppingCart,
  ShoppingBag,
  UtensilsCrossed,
  Utensils,
  Coffee,
  Carrot,
  Palette,
  Paintbrush,
  Music,
  Guitar,
  Mic,
  Camera,
  Video,
  Gamepad2,
  Car,
  Bus,
  Train,
  Plane,
  MapPin,
  Globe,
  Users,
  User,
  PawPrint,
  Leaf,
  Sprout,
  Sun,
  CloudRain,
  Target,
  Flag,
  Clock,
  Timer,
  Calendar,
  CalendarCheck,
  ListChecks,
  Repeat,
  Zap,
  Sparkles,
  KanbanSquare,
  Star,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  Briefcase, Wallet, DollarSign, PiggyBank, TrendingUp, Coins,
  Dumbbell, Bike, Footprints, Activity, Trophy, Flame, Mountain, Waves,
  Heart, HeartPulse, Pill, Stethoscope, Brain, Moon, Bed, Droplet, Baby,
  GraduationCap, BookOpen, NotebookPen, Languages,
  Home, Wrench, ShoppingCart, ShoppingBag, UtensilsCrossed, Utensils, Coffee, Carrot,
  Palette, Paintbrush, Music, Guitar, Mic, Camera, Video, Gamepad2,
  Car, Bus, Train, Plane, MapPin, Globe,
  Users, User, PawPrint, Leaf, Sprout, Sun, CloudRain,
  Target, Flag, Clock, Timer, Calendar, CalendarCheck, ListChecks, Repeat,
  Zap, Sparkles, KanbanSquare, Star,
};
